homework
Galina313/Heroku_QA_tests pull request #1
Opened 2024-11-20 00:12 UTC by Galina313

Добавляла много где  await driver.sleep(...), так как хотела посмотреть, как в браузере проходит тест. Без sleep всё было очень быстро)

2024-11-20 13:21 UTC, voropa commented
> Добавляла много где await driver.sleep(...), так как хотела посмотреть, как в браузере проходит тест. Без sleep всё было очень быстро)

Когда посмотрели,  убедились, что все работает, sleep() нужно убрать из кода. Сделайте это, пожалуйста

2024-11-20 13:24 UTC, voropa requested changes

2024-11-20 13:24 UTC, voropa commented on tests/herokuapp.spec.ts
> +    const driver = await new Builder().forBrowser(Browser.EDGE).build();
Два действя на строках 149-150 лишние, у вас уже и так драйвер инициализируетс в beforeEach()

2024-11-20 13:24 UTC, voropa commented on tests/herokuapp.spec.ts
> +    const iframetext = await driver.wait(
Хмм, такой тест работает?
По зданию нужно переклбючиться в IfRame с помощью driver.switchTo().iframe() и потом дотсать из него текст

2024-12-09 09:06 UTC, Galina313 commented
> > Добавляла много где await driver.sleep(...), так как хотела посмотреть, как в браузере проходит тест. Без sleep всё было очень быстро)
> 
> Когда посмотрели, убедились, что все работает, sleep() нужно убрать из кода. Сделайте это, пожалуйста

Сделала, закоммитила фикс

2024-12-09 09:06 UTC, Galina313 commented on tests/herokuapp.spec.ts
> +    const iframetext = await driver.wait(
Исправила, закоммитила фикс

2024-12-09 09:06 UTC, Galina313 commented on tests/herokuapp.spec.ts
> +    const driver = await new Builder().forBrowser(Browser.EDGE).build();
Исправила, закоммитила фикс

2024-12-09 10:01 UTC, voropa approved these changes

2024-12-09 11:36 UTC, merged